services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
      - uploaded_files:/app/uploads
    depends_on:
      - db

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    depends_on:
      - api

volumes:
  backend_node_modules:
  uploaded_files:
  frontend_node_modules: